project_id = "awbkbvpayomkauubomdo"

[functions.admin-bot]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.send-moderation]
verify_jwt = false

[functions.send-edit-moderation]
verify_jwt = false

[functions.tg-reviews]
verify_jwt = false