project_id = "symhqwyycpnnwterfgxt"

[functions.ai-assistant]
verify_jwt = false

[functions.admin-bot]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.cryptobot-webhook]
verify_jwt = false

[functions.send-moderation]
verify_jwt = false

[functions.send-edit-moderation]
verify_jwt = false

[functions.stars-create-invoice]
verify_jwt = false

[functions.manual-payment]
verify_jwt = false
